import pool from "@/lib/db";
import { NextRequest, NextResponse } from "next/server";
const ID = {
    // users
    user1: "11111111-1111-1111-1111-000000000001",
    user2: "11111111-1111-1111-1111-000000000002",
    user3: "11111111-1111-1111-1111-000000000003",
    // categories
    cat1: "22222222-2222-2222-2222-000000000001",
    cat2: "22222222-2222-2222-2222-000000000002",
    cat3: "22222222-2222-2222-2222-000000000003",
    cat4: "22222222-2222-2222-2222-000000000004",
    // products
    prod1: "33333333-3333-3333-3333-000000000001",
    prod2: "33333333-3333-3333-3333-000000000002",
    prod3: "33333333-3333-3333-3333-000000000003",
    prod4: "33333333-3333-3333-3333-000000000004",
    prod5: "33333333-3333-3333-3333-000000000005",
    // cart items
    cart1: "44444444-4444-4444-4444-000000000001",
    cart2: "44444444-4444-4444-4444-000000000002",
    cart3: "44444444-4444-4444-4444-000000000003",
    // orders
    ord1: "55555555-5555-5555-5555-000000000001",
    ord2: "55555555-5555-5555-5555-000000000002",
    // order items
    oi1: "66666666-6666-6666-6666-000000000001",
    oi2: "66666666-6666-6666-6666-000000000002",
    oi3: "66666666-6666-6666-6666-000000000003",
    // favorites
    fav1: "77777777-7777-7777-7777-000000000001",
    fav2: "77777777-7777-7777-7777-000000000002",
    fav3: "77777777-7777-7777-7777-000000000003",
};



const products = [
    {
        name: "Chemise Oxford Slim",
        slug: "chemise-oxford-slim",
        description: "Chemise Oxford coupe slim, idéale pour le bureau ou les sorties.",
        price: 15000,
        category_id: ID.cat1,
        image_url: "/images/img-24.jpg",
        images: [
            { url: "/images/img-24.jpg", name: "Face", alt: "Veste face", width: 4000, height: 6000 },
            { url: "/images/img-11.jpg", name: "Face", alt: "Veste face", width: 3648, height: 3648 },
            { url: "/images/img-25.jpg", name: "Dos", alt: "Veste dos", width: 2339, height: 3508 }
        ],
        size: ["S", "M", "L", "XL"],
        color: ["#FFFFFF", "#679FFA", "#87CEEB"],
        stock: 45,
        is_new: true,
        is_promo: false,
        discount_price: null,
        discount_percentage: null,
    },
    {
        name: "Robe Wax Imprimé",
        slug: "robe-wax-imprime",
        description: "Magnifique robe en tissu wax africain, coupe droite, col rond.",
        price: 22000,
        category_id: ID.cat2,
        image_url: "/images/img-31.jpg",
        images: [
            { url: "/images/img-31.jpg", name: "Face", alt: "Veste face", width: 3648, height: 3648 },
            { url: "/images/img-38.jpg", name: "Face", alt: "Veste face", width: 4160, height: 6240 },
            { url: "/images/img-33.jpg", name: "Dos", alt: "Veste dos", width: 2848, height: 4288 }
        ],
        size: ["S", "M", "L", "XL", "XXL"],
        color: ["#FF6B6B", "#FFD600", "#E53935"],
        stock: 30,
        is_new: true,
        is_promo: true,
        discount_price: 18000,
        discount_percentage: 18,
    },
    {
        name: "Sneakers Urban Runner",
        slug: "sneakers-urban-runner",
        description: "Sneakers légères et confortables pour un style urbain au quotidien.",
        price: 28000,
        category_id: ID.cat3,
        image_url: "/images/img-29.jpg",
        images: [
            { url: "/images/img-29.jpg", name: "Face", alt: "Veste face", width: 3386, height: 6020 },
            { url: "/images/img-27.jpg", name: "Face", alt: "Veste face", width: 3024, height: 4032 },
            { url: "/images/img-28.jpg", name: "Dos", alt: "Veste dos", width: 4160, height: 6240 }
        ],
        size: ["38", "39", "40", "41", "42", "43", "44"],
        color: ["#1A1A1A", "#FFFFFF", "#D4B896"],
        stock: 60,
        is_new: false,
        is_promo: true,
        discount_price: 23000,
        discount_percentage: 18,
    },

    {
        name: "Jean Slim Denim",
        slug: "jean-slim-denim",
        description: "Jean slim stretch, confortable et tendance pour un look moderne.",
        price: 18000,
        category_id: ID.cat1,
        image_url: "/images/img-01.jpg",
        images: [
            { url: "/images/img-01.jpg", name: "Face", alt: "Jean face", width: 3000, height: 4000 },
            { url: "/images/img-10.jpg", name: "Dos", alt: "Jean dos", width: 3000, height: 4000 }
        ],
        size: ["38", "40", "42", "44"],
        color: ["#1A1A1A", "#0D47A1"],
        stock: 55,
        is_new: true,
        is_promo: false,
        discount_price: null,
        discount_percentage: null,
    },
    {
        name: "Sandales Confort",
        slug: "sandales-confort",
        description: "Sandales légères idéales pour les journées chaudes.",
        price: 9500,
        category_id: ID.cat3,
        image_url: "/images/img-12.jpg",
        images: [
            { url: "/images/img-12.jpg", name: "Face", alt: "Sandales", width: 3000, height: 3000 }
        ],
        size: ["39", "40", "41", "42"],
        color: ["#795548", "#000000"],
        stock: 70,
        is_new: false,
        is_promo: true,
        discount_price: 8000,
        discount_percentage: 15,
    },
    {
        name: "Montre Élégante",
        slug: "montre-elegante",
        description: "Montre design avec bracelet cuir pour un style chic.",
        price: 25000,
        category_id: ID.cat4,
        image_url: "/images/img-35.jpg",
        images: [
            { url: "/images/img-35.jpg", name: "Face", alt: "Montre", width: 3000, height: 3000 }
        ],
        size: [],
        color: ["#000000", "#C0C0C0"],
        stock: 25,
        is_new: true,
        is_promo: false,
        discount_price: null,
        discount_percentage: null,
    },
    {
        name: "Jupe Midi Chic",
        slug: "jupe-midi-chic",
        description: "Jupe midi fluide parfaite pour le bureau ou les sorties.",
        price: 14000,
        category_id: ID.cat2,
        image_url: "/images/img-41.jpg",
        images: [
            { url: "/images/img-41.jpg", name: "Face", alt: "Jupe", width: 3000, height: 4000 }
        ],
        size: ["S", "M", "L"],
        color: ["#E91E63", "#000000"],
        stock: 35,
        is_new: false,
        is_promo: false,
        discount_price: null,
        discount_percentage: null,
    },
    {
        name: "Veste Casual",
        slug: "veste-casual",
        description: "Veste légère parfaite pour les soirées fraîches.",
        price: 27000,
        category_id: ID.cat1,
        image_url: "/images/img-03.jpg",
        images: [
            { url: "/images/img-03.jpg", name: "Face", alt: "Veste", width: 3000, height: 4000 }
        ],
        size: ["M", "L", "XL"],
        color: ["#3E2723", "#1A1A1A"],
        stock: 20,
        is_new: true,
        is_promo: true,
        discount_price: 23000,
        discount_percentage: 15,
    },
    {
        name: "Talons Élégants",
        slug: "talons-elegants",
        description: "Chaussures à talons pour un look sophistiqué.",
        price: 21000,
        category_id: ID.cat3,
        image_url: "/images/img-04.jpg",
        images: [
            { url: "/images/img-04.jpg", name: "Face", alt: "Talons", width: 3000, height: 4000 }
        ],
        size: ["37", "38", "39", "40"],
        color: ["#000000", "#FF6B6B"],
        stock: 40,
        is_new: false,
        is_promo: true,
        discount_price: 18000,
        discount_percentage: 14,
    },
    {
        name: "Sac à Dos Urbain",
        slug: "sac-a-dos-urbain",
        description: "Sac à dos pratique pour école ou travail.",
        price: 16000,
        category_id: ID.cat4,
        image_url: "/images/img-05.jpg",
        images: [
            { url: "/images/img-05.jpg", name: "Face", alt: "Sac", width: 3000, height: 4000 }
        ],
        size: [],
        color: ["#000000", "#455A64"],
        stock: 50,
        is_new: true,
        is_promo: false,
        discount_price: null,
        discount_percentage: null,
    },
    {
        name: "Blouse Élégante",
        slug: "blouse-elegante",
        description: "Blouse légère parfaite pour toutes occasions.",
        price: 13000,
        category_id: ID.cat2,
        image_url: "/images/img-06.jpg",
        images: [
            { url: "/images/img-06.jpg", name: "Face", alt: "Blouse", width: 3000, height: 4000 }
        ],
        size: ["S", "M", "L"],
        color: ["#FFFFFF", "#FFB6C1"],
        stock: 45,
        is_new: true,
        is_promo: false,
        discount_price: null,
        discount_percentage: null,
    },
    {
        name: "Basket Sport Pro",
        slug: "basket-sport-pro",
        description: "Chaussures de sport performantes et respirantes.",
        price: 30000,
        category_id: ID.cat3,
        image_url: "/images/img-07.jpg",
        images: [
            { url: "/images/img-07.jpg", name: "Face", alt: "Basket", width: 3000, height: 4000 }
        ],
        size: ["40", "41", "42", "43", "44"],
        color: ["#000000", "#2196F3"],
        stock: 60,
        is_new: true,
        is_promo: true,
        discount_price: 26000,
        discount_percentage: 13,
    },
    {
        name: "Ceinture Cuir Premium",
        slug: "ceinture-cuir-premium",
        description: "Ceinture en cuir véritable pour un style classe.",
        price: 11000,
        category_id: ID.cat4,
        image_url: "/images/img-09.jpg",
        images: [
            { url: "/images/img-09.jpg", name: "Face", alt: "Ceinture", width: 3000, height: 3000 }
        ],
        size: ["M", "L", "XL"],
        color: ["#3E2723", "#000000"],
        stock: 75,
        is_new: false,
        is_promo: false,
        discount_price: null,
        discount_percentage: null,
    },
    {
        name: "Mocassins en Daim",
        slug: "mocassins-daim-luxe",
        description: "Mocassins élégants en daim véritable, parfaits pour un look chic-décontracté.",
        price: 35000,
        category_id: ID.cat3,
        image_url: "/images/img-10.jpg",
        images: [
            { url: "/images/img-10.jpg", name: "Face", alt: "Mocassins face", width: 4000, height: 6000 },
            { url: "/images/img-40.jpg", name: "Profil", alt: "Mocassins profil", width: 4000, height: 6000 }
        ],
        size: ["40", "41", "42", "43", "44", "45"],
        color: ["#4E342E", "#1A1A1A"],
        stock: 15,
        is_new: true,
        is_promo: false,
        discount_price: null,
        discount_percentage: null,
    },

    {
        name: "Montre Minimaliste",
        slug: "montre-minimaliste-cuir",
        description: "Montre à quartz avec bracelet en cuir noir et cadran épuré.",
        price: 45000,
        category_id: ID.cat4,
        image_url: "/images/img-11.jpg",
        images: [
            { url: "/images/img-11.jpg", name: "Zoom", alt: "Montre zoom", width: 2000, height: 2000 }
        ],
        size: [],
        color: ["#000000", "#C0C0C0"],
        stock: 10,
        is_new: true,
        is_promo: false,
        discount_price: null,
        discount_percentage: null,
    },
    {
        name: "Pantalon Chino Slim",
        slug: "pantalon-chino-slim",
        description: "Pantalon chino en coton stretch, coupe ajustée, plusieurs coloris disponibles.",
        price: 17000,
        category_id: ID.cat1,
        image_url: "/images/img-12.jpg",
        images: [
            { url: "/images/img-12.jpg", name: "Face", alt: "Chino face", width: 3000, height: 4500 }
        ],
        size: ["30", "32", "34", "36", "38"],
        color: ["#5D4037", "#263238", "#ECEFF1"],
        stock: 50,
        is_new: false,
        is_promo: false,
        discount_price: null,
        discount_percentage: null,
    },
    {
        name: "Blouse en Soie",
        slug: "blouse-soie-elegance",
        description: "Blouse 100% soie, col en V, idéale pour les grandes occasions.",
        price: 29000,
        category_id: ID.cat2,
        image_url: "/images/img-13.jpg",
        images: [
            { url: "/images/img-13.jpg", name: "Face", alt: "Blouse face", width: 3200, height: 4800 }
        ],
        size: ["M", "L", "XL"],
        color: ["#E1BEE7", "#FFFFFF"],
        stock: 12,
        is_new: true,
        is_promo: true,
        discount_price: 24500,
        discount_percentage: 15,
    },
    {
        name: "Ceinture Cuir Classique",
        slug: "ceinture-cuir-classique",
        description: "Ceinture robuste en cuir de vachette avec boucle en acier brossé.",
        price: 8500,
        category_id: ID.cat4,
        image_url: "/images/img-14.jpg",
        images: [
            { url: "/images/img-14.jpg", name: "Face", alt: "Ceinture", width: 2500, height: 2500 }
        ],
        size: ["90", "95", "100", "105"],
        color: ["#3E2723", "#000000"],
        stock: 100,
        is_new: false,
        is_promo: false,
        discount_price: null,
        discount_percentage: null,
    },
    {
        name: "Sandales d'Été",
        slug: "sandales-ete-confort",
        description: "Sandales légères avec semelle ergonomique pour de longues marches.",
        price: 14000,
        category_id: ID.cat3,
        image_url: "/images/img-15.jpg",
        images: [
            { url: "/images/img-15.jpg", name: "Face", alt: "Sandales", width: 3000, height: 3000 }
        ],
        size: ["37", "38", "39", "40", "41"],
        color: ["#D7CCC8", "#FFFFFF"],
        stock: 40,
        is_new: false,
        is_promo: true,
        discount_price: 11000,
        discount_percentage: 21,
    },

    {
        name: "Polo Classic Fit",
        slug: "polo-classic-fit",
        description: "Polo en coton piqué, col boutonné, coupe classique confortable.",
        price: 12000,
        category_id: ID.cat1,
        image_url: "/images/img-39.jpg",
        images: [
            { url: "/images/img-39.jpg", name: "Face", alt: "Polo face", width: 2935, height: 3894 },
            { url: "/images/img-41.jpg", name: "Détail", alt: "Polo détail", width: 4000, height: 6000 },
            { url: "/images/img-40.jpg", name: "Dos", alt: "Polo dos", width: 3712, height: 5568 },
            { url: "/images/img-30.jpg", name: "Style", alt: "Polo style", width: 3712, height: 5568 },
        ],
        size: ["S", "M", "L", "XL"],
        color: ["#FFFFFF", "#1A237E", "#E53935", "#388E3C"],
        stock: 80,
        is_new: false,
        is_promo: false,
        discount_price: null,
        discount_percentage: null,
    },
    {
        name: "Pantalon Chino Stretch",
        slug: "pantalon-chino-stretch",
        description: "Pantalon chino stretch coupe droite, confortable pour toute la journée.",
        price: 18000,
        category_id: ID.cat1,
        image_url: "/images/img-chino-01.jpg",
        images: [
            { url: "/images/img-chino-01.jpg", name: "Face", alt: "Chino face", width: 3000, height: 4500 },
            { url: "/images/img-chino-02.jpg", name: "Dos", alt: "Chino dos", width: 3000, height: 4500 },
        ],
        size: ["38", "40", "42", "44", "46"],
        color: ["#C8A96E", "#3E3E3E", "#4A6741"],
        stock: 55,
        is_new: false,
        is_promo: true,
        discount_price: 14500,
        discount_percentage: 19,
    },
    {
        name: "Veste Légère Bomber",
        slug: "veste-legere-bomber",
        description: "Bomber léger tendance, parfait pour les soirées fraîches.",
        price: 32000,
        category_id: ID.cat1,
        image_url: "/images/img-11.jpg",
        images: [
            { url: "/images/img-11.jpg", name: "Face", alt: "Bomber face", width: 3500, height: 5250 },
            { url: "/images/img-12.jpg", name: "Dos", alt: "Bomber dos", width: 3500, height: 5250 },
        ],
        size: ["S", "M", "L", "XL", "XXL"],
        color: ["#1A1A1A", "#2C3E50", "#8B0000"],
        stock: 25,
        is_new: true,
        is_promo: false,
        discount_price: null,
        discount_percentage: null,
    },
    {
        name: "T-Shirt Oversize Graphique",
        slug: "tshirt-oversize-graphique",
        description: "T-shirt oversize 100% coton avec imprimé graphique urbain.",
        price: 9500,
        category_id: ID.cat1,
        image_url: "/images/img-31.jpg",
        images: [
            { url: "/images/img-31.jpg", name: "Face", alt: "Tshirt face", width: 3000, height: 4000 },
            { url: "/images/img-32.jpg", name: "Dos", alt: "Tshirt dos", width: 3000, height: 4000 },
        ],
        size: ["S", "M", "L", "XL", "XXL"],
        color: ["#FFFFFF", "#E0E0E0", "#1A1A1A"],
        stock: 100,
        is_new: true,
        is_promo: false,
        discount_price: null,
        discount_percentage: null,
    },

    // ── VÊTEMENTS FEMMES ──────────────────────────────────────────

    {
        name: "Blouse Légère Fleurie",
        slug: "blouse-legere-fleurie",
        description: "Blouse fluide à motifs floraux, idéale pour les journées chaudes.",
        price: 14500,
        category_id: ID.cat2,
        image_url: "/images/img-blouse-01.jpg",
        images: [
            { url: "/images/img-blouse-01.jpg", name: "Face", alt: "Blouse face", width: 3000, height: 4500 },
            { url: "/images/img-blouse-02.jpg", name: "Dos", alt: "Blouse dos", width: 3000, height: 4500 },
        ],
        size: ["XS", "S", "M", "L", "XL"],
        color: ["#FFF9C4", "#FCE4EC", "#E8F5E9"],
        stock: 40,
        is_new: true,
        is_promo: false,
        discount_price: null,
        discount_percentage: null,
    },
    {
        name: "Jupe Plissée Midi",
        slug: "jupe-plissee-midi",
        description: "Jupe plissée longueur midi, élégante et polyvalente.",
        price: 16000,
        category_id: ID.cat2,
        image_url: "/images/img-21.jpg",
        images: [
            { url: "/images/img-21.jpg", name: "Face", alt: "Jupe face", width: 3000, height: 4500 },
            { url: "/images/img-22.jpg", name: "Détail", alt: "Jupe détail", width: 3000, height: 4500 },
        ],
        size: ["XS", "S", "M", "L", "XL"],
        color: ["#E91E63", "#9C27B0", "#263238"],
        stock: 35,
        is_new: false,
        is_promo: true,
        discount_price: 12800,
        discount_percentage: 20,
    },
    {
        name: "Combinaison Pantalon Chic",
        slug: "combinaison-pantalon-chic",
        description: "Combinaison pantalon élégante, parfaite pour les événements.",
        price: 27000,
        category_id: ID.cat2,
        image_url: "/images/img-31.jpg",
        images: [
            { url: "/images/img-31.jpg", name: "Face", alt: "Combinaison face", width: 3500, height: 5250 },
            { url: "/images/img-32.jpg", name: "Dos", alt: "Combinaison dos", width: 3500, height: 5250 },
        ],
        size: ["XS", "S", "M", "L", "XL"],
        color: ["#1A1A1A", "#F5F5F5", "#BF9B30"],
        stock: 18,
        is_new: true,
        is_promo: false,
        discount_price: null,
        discount_percentage: null,
    },
    {
        name: "Top Brodé Africain",
        slug: "top-brode-africain",
        description: "Top à broderies africaines colorées, 100% coton.",
        price: 11000,
        category_id: ID.cat2,
        image_url: "/images/img-11.jpg",
        images: [
            { url: "/images/img-11.jpg", name: "Face", alt: "Top face", width: 3000, height: 4000 },
            { url: "/images/img-13.jpg", name: "Dos", alt: "Top dos", width: 3000, height: 4000 },
        ],
        size: ["XS", "S", "M", "L"],
        color: ["#FF8F00", "#FFFFFF", "#1565C0"],
        stock: 50,
        is_new: false,
        is_promo: false,
        discount_price: null,
        discount_percentage: null,
    },


    {
        name: "Mocassins Premium",
        slug: "mocassins-premium",
        description: "Mocassins en cuir souple, semelle légère, style bureau et casual.",
        price: 24000,
        category_id: ID.cat3,
        image_url: "/images/img-27.jpg",
        images: [
            { url: "/images/img-27.jpg", name: "Dessus", alt: "Mocassins dessus", width: 3000, height: 3500 },
            { url: "/images/img-28.jpg", name: "Profil", alt: "Mocassins profil", width: 3000, height: 3500 },
        ],
        size: ["40", "41", "42", "43", "44", "45"],
        color: ["#795548", "#1A1A1A", "#C8A96E"],
        stock: 30,
        is_new: false,
        is_promo: true,
        discount_price: 19500,
        discount_percentage: 19,
    },
    {
        name: "Chaussures de Sport Pro",
        slug: "chaussures-sport-pro",
        description: "Chaussures running haute performance, semelle amortissante.",
        price: 35000,
        category_id: ID.cat3,
        image_url: "/images/img-28.jpg",
        images: [
            { url: "/images/img-28.jpg", name: "Face", alt: "Chaussures sport face", width: 3500, height: 5000 },
            { url: "/images/img-29.jpg", name: "Semelle", alt: "Chaussures sport semelle", width: 3500, height: 5000 },
        ],
        size: ["38", "39", "40", "41", "42", "43", "44", "45"],
        color: ["#E53935", "#1E88E5", "#1A1A1A"],
        stock: 50,
        is_new: true,
        is_promo: false,
        discount_price: null,
        discount_percentage: null,
    },
    {
        name: "Talons Aiguilles Élégants",
        slug: "talons-aiguilles-elegants",
        description: "Escarpins à talons aiguilles, bout pointu, finition vernie.",
        price: 21000,
        category_id: ID.cat3,
        image_url: "/images/img-31.jpg",
        images: [
            { url: "/images/img-31.jpg", name: "Face", alt: "Talons face", width: 3000, height: 4500 },
            { url: "/images/img-32.jpg", name: "Profil", alt: "Talons profil", width: 3000, height: 4500 },
        ],
        size: ["36", "37", "38", "39", "40"],
        color: ["#1A1A1A", "#C8A96E", "#E53935"],
        stock: 22,
        is_new: false,
        is_promo: false,
        discount_price: null,
        discount_percentage: null,
    },

    // ── ACCESSOIRES ───────────────────────────────────────────────
    {
        name: "Sac Bandoulière Cuir",
        slug: "sac-bandouliere-cuir",
        description: "Sac bandoulière en cuir synthétique, compact et élégant.",
        price: 19500,
        category_id: ID.cat4,
        image_url: "/images/img-16.jpg",
        images: [
            { url: "/images/img-16.jpg", name: "Face", alt: "Sac face", width: 2935, height: 3894 },
            { url: "/images/img-21.jpg", name: "Intérieur", alt: "Sac intérieur", width: 4000, height: 6000 },
            { url: "/images/img-20.jpg", name: "Dos", alt: "Sac dos", width: 3712, height: 5568 },
        ],
        size: [],
        color: ["#795548", "#1A1A1A", "#C8864E"],
        stock: 20,
        is_new: false,
        is_promo: false,
        discount_price: null,
        discount_percentage: null,
    },
    {
        name: "Montre Classique Dorée",
        slug: "montre-classique-doree",
        description: "Montre analogique boîtier doré, bracelet en cuir, mouvement à quartz.",
        price: 42000,
        category_id: ID.cat4,
        image_url: "/images/img-21.jpg",
        images: [
            { url: "/images/img-21.jpg", name: "Face", alt: "Montre face", width: 3000, height: 3000 },
            { url: "/images/img-22.jpg", name: "Profil", alt: "Montre profil", width: 3000, height: 3000 },
        ],
        size: [],
        color: ["#BF9B30", "#C0C0C0"],
        stock: 15,
        is_new: true,
        is_promo: false,
        discount_price: null,
        discount_percentage: null,
    },
    {
        name: "Ceinture Cuir Tressé",
        slug: "ceinture-cuir-tresse",
        description: "Ceinture tressée en cuir véritable, boucle argentée classique.",
        price: 8500,
        category_id: ID.cat4,
        image_url: "/images/img-30.jpg",
        images: [
            { url: "/images/img-30.jpg", name: "Face", alt: "Ceinture face", width: 4000, height: 2000 },
            { url: "/images/img-31.jpg", name: "Détail", alt: "Ceinture détail", width: 3000, height: 2000 },
        ],
        size: ["S", "M", "L", "XL"],
        color: ["#795548", "#1A1A1A"],
        stock: 70,
        is_new: false,
        is_promo: true,
        discount_price: 6500,
        discount_percentage: 24,
    },
    {
        name: "Sac à Main Wax",
        slug: "sac-main-wax",
        description: "Sac à main artisanal en tissu wax, doublure en coton, fermeture zippée.",
        price: 15000,
        category_id: ID.cat4,
        image_url: "/images/img-01.jpg",
        images: [
            { url: "/images/img-01.jpg", name: "Face", alt: "Sac wax face", width: 3000, height: 4000 },
            { url: "/images/img-02.jpg", name: "Ouvert", alt: "Sac wax ouvert", width: 3000, height: 4000 },
        ],
        size: [],
        color: ["#FF6B6B", "#FFD600", "#4CAF50"],
        stock: 28,
        is_new: true,
        is_promo: false,
        discount_price: null,
        discount_percentage: null,
    },
    {
        name: "Collier Perles Africaines",
        slug: "collier-perles-africaines",
        description: "Collier artisanal en perles colorées, style africain tendance.",
        price: 6500,
        category_id: ID.cat4,
        image_url: "/images/img-33.jpg",
        images: [
            { url: "/images/img-33.jpg", name: "Face", alt: "Collier face", width: 3000, height: 3000 },
            { url: "/images/img-32.jpg", name: "Porté", alt: "Collier porté", width: 3000, height: 4000 },
        ],
        size: [],
        color: ["#FF6B6B", "#FFD600", "#1565C0", "#388E3C"],
        stock: 90,
        is_new: false,
        is_promo: false,
        discount_price: null,
        discount_percentage: null,
    },
    {
        name: "Lunettes de Soleil Aviateur",
        slug: "lunettes-soleil-aviateur",
        description: "Lunettes aviateur protection UV400, monture dorée, verres teintés.",
        price: 12000,
        category_id: ID.cat4,
        image_url: "/images/img-01.jpg",
        images: [
            { url: "/images/img-01.jpg", name: "Face", alt: "Lunettes face", width: 3000, height: 2000 },
            { url: "/images/img-02.jpg", name: "Portées", alt: "Lunettes portées", width: 3000, height: 4000 },
        ],
        size: [],
        color: ["#BF9B30", "#C0C0C0", "#1A1A1A"],
        stock: 45,
        is_new: true,
        is_promo: true,
        discount_price: 9500,
        discount_percentage: 21,
    },


    // --- Vêtements Hommes (cat1) ---
    {
        name: "Veste Blazer Lin",
        slug: "veste-blazer-lin",
        description: "Blazer en lin léger, parfait pour les soirées et événements formels.",
        price: 35000,
        category_id: ID.cat1,
        image_url: "/images/img-01.jpg",
        images: [
            { url: "/images/img-01.jpg", name: "Face", alt: "Blazer face", width: 4000, height: 6000 },
            { url: "/images/img-02.jpg", name: "Côté", alt: "Blazer côté", width: 4000, height: 6000 },
            { url: "/images/img-03.jpg", name: "Dos", alt: "Blazer dos", width: 4000, height: 6000 },
        ],
        size: ["S", "M", "L", "XL", "XXL"],
        color: ["#D2B48C", "#1A1A1A", "#ECEFF1"],
        stock: 25,
        is_new: true,
        is_promo: false,
        discount_price: null,
        discount_percentage: null,
    },

    {
        name: "T-Shirt Oversize Premium",
        slug: "tshirt-oversize-premium",
        description: "T-shirt oversize en coton 100 %, col rond, coupe décontractée.",
        price: 8500,
        category_id: ID.cat1,
        image_url: "/images/img-07.jpg",
        images: [
            { url: "/images/img-07.jpg", name: "Face", alt: "T-shirt face", width: 4000, height: 6000 },
            { url: "/images/img-08.jpg", name: "Dos", alt: "T-shirt dos", width: 4000, height: 6000 },
        ],
        size: ["S", "M", "L", "XL", "XXL"],
        color: ["#FFFFFF", "#1A1A1A", "#B0BEC5", "#A5D6A7"],
        stock: 120,
        is_new: true,
        is_promo: false,
        discount_price: null,
        discount_percentage: null,
    },

    // --- Vêtements Femmes (cat2) ---
    {
        name: "Blouse Brodée Boubou",
        slug: "blouse-brodee-boubou",
        description: "Blouse longue style boubou avec broderies dorées sur le col et les manches.",
        price: 27000,
        category_id: ID.cat2,
        image_url: "/images/img-09.jpg",
        images: [
            { url: "/images/img-09.jpg", name: "Face", alt: "Blouse face", width: 4160, height: 6240 },
            { url: "/images/img-10.jpg", name: "Détail", alt: "Blouse détail", width: 4160, height: 6240 },
            { url: "/images/img-11.jpg", name: "Dos", alt: "Blouse dos", width: 3648, height: 3648 },
        ],
        size: ["S", "M", "L", "XL", "XXL"],
        color: ["#FFF9C4", "#CE93D8", "#80DEEA"],
        stock: 18,
        is_new: true,
        is_promo: false,
        discount_price: null,
        discount_percentage: null,
    },
    {
        name: "Jupe Midi Wax",
        slug: "jupe-midi-wax",
        description: "Jupe midi taille haute en wax, fermeture éclair invisible, coupe évasée.",
        price: 14500,
        category_id: ID.cat2,
        image_url: "/images/img-12.jpg",
        images: [
            { url: "/images/img-12.jpg", name: "Face", alt: "Jupe face", width: 3648, height: 5472 },
            { url: "/images/img-13.jpg", name: "Côté", alt: "Jupe côté", width: 3648, height: 5472 },
            { url: "/images/img-14.jpg", name: "Dos", alt: "Jupe dos", width: 3648, height: 5472 },
        ],
        size: ["XS", "S", "M", "L", "XL"],
        color: ["#FF8F00", "#43A047", "#E53935"],
        stock: 35,
        is_new: false,
        is_promo: true,
        discount_price: 11000,
        discount_percentage: 24,
    },
    {
        name: "Robe Cocktail Dentelle",
        slug: "robe-cocktail-dentelle",
        description: "Robe courte en dentelle, col V, idéale pour les soirées et occasions spéciales.",
        price: 32000,
        category_id: ID.cat2,
        image_url: "/images/img-15.jpg",
        images: [
            { url: "/images/img-15.jpg", name: "Face", alt: "Robe face", width: 4000, height: 6000 },
            { url: "/images/img-16.jpg", name: "Côté", alt: "Robe côté", width: 2935, height: 3894 },
            { url: "/images/img-17.jpg", name: "Dos", alt: "Robe dos", width: 4000, height: 6000 },
        ],
        size: ["XS", "S", "M", "L"],
        color: ["#1A1A1A", "#C62828", "#4A148C"],
        stock: 12,
        is_new: true,
        is_promo: false,
        discount_price: null,
        discount_percentage: null,
    },

    // --- Chaussures (cat3) ---
    {
        name: "Sandales Tressées Cuir",
        slug: "sandales-tressees-cuir",
        description: "Sandales plates tressées en cuir véritable, confort toute la journée.",
        price: 16500,
        category_id: ID.cat3,
        image_url: "/images/img-18.jpg",
        images: [
            { url: "/images/img-18.jpg", name: "Face", alt: "Sandales face", width: 4000, height: 6000 },
            { url: "/images/img-19.jpg", name: "Semelle", alt: "Sandales semelle", width: 4000, height: 6000 },
            { url: "/images/img-20.jpg", name: "Côté", alt: "Sandales côté", width: 3712, height: 5568 },
        ],
        size: ["36", "37", "38", "39", "40", "41"],
        color: ["#C8864E", "#1A1A1A", "#D2B48C"],
        stock: 40,
        is_new: false,
        is_promo: false,
        discount_price: null,
        discount_percentage: null,
    },
    {
        name: "Mocassins Loafer Premium",
        slug: "mocassins-loafer-premium",
        description: "Mocassins élégants en cuir, semelle souple, idéaux pour le bureau.",
        price: 24000,
        category_id: ID.cat3,
        image_url: "/images/img-21.jpg",
        images: [
            { url: "/images/img-21.jpg", name: "Face", alt: "Mocassins face", width: 4000, height: 6000 },
            { url: "/images/img-22.jpg", name: "Côté", alt: "Mocassins côté", width: 4000, height: 6000 },
            { url: "/images/img-23.jpg", name: "Dos", alt: "Mocassins dos", width: 4000, height: 6000 },
        ],
        size: ["39", "40", "41", "42", "43", "44", "45"],
        color: ["#795548", "#1A1A1A"],
        stock: 30,
        is_new: false,
        is_promo: true,
        discount_price: 19500,
        discount_percentage: 19,
    },
    {
        name: "Baskets Running Pro",
        slug: "baskets-running-pro",
        description: "Chaussures de running haute performance, semelle à absorption de chocs.",
        price: 38000,
        category_id: ID.cat3,
        image_url: "/images/img-26.jpg",
        images: [
            { url: "/images/img-26.jpg", name: "Face", alt: "Baskets face", width: 4000, height: 6000 },
            { url: "/images/img-27.jpg", name: "Côté", alt: "Baskets côté", width: 3024, height: 4032 },
            { url: "/images/img-28.jpg", name: "Dos", alt: "Baskets dos", width: 4160, height: 6240 },
        ],
        size: ["38", "39", "40", "41", "42", "43", "44", "45"],
        color: ["#E53935", "#1A1A1A", "#1565C0"],
        stock: 50,
        is_new: true,
        is_promo: false,
        discount_price: null,
        discount_percentage: null,
    },

    // --- Accessoires (cat4) ---
    {
        name: "Montre Solaire Acier",
        slug: "montre-solaire-acier",
        description: "Montre à cadran solaire, boîtier en acier inoxydable, bracelet en cuir.",
        price: 45000,
        category_id: ID.cat4,
        image_url: "/images/img-32.jpg",
        images: [
            { url: "/images/img-32.jpg", name: "Face", alt: "Montre face", width: 4000, height: 4000 },
            { url: "/images/img-34.jpg", name: "Profil", alt: "Montre profil", width: 4000, height: 4000 },
            { url: "/images/img-35.jpg", name: "Bracelet", alt: "Montre bracelet", width: 4000, height: 4000 },
        ],
        size: [],
        color: ["#C0C0C0", "#FFD700", "#1A1A1A"],
        stock: 15,
        is_new: true,
        is_promo: false,
        discount_price: null,
        discount_percentage: null,
    },
    {
        name: "Ceinture Tressée Cuir",
        slug: "ceinture-tressee-cuir",
        description: "Ceinture tressée en cuir véritable, boucle argentée, plusieurs tailles.",
        price: 9500,
        category_id: ID.cat4,
        image_url: "/images/img-36.jpg",
        images: [
            { url: "/images/img-36.jpg", name: "Face", alt: "Ceinture face", width: 4000, height: 2000 },
            { url: "/images/img-37.jpg", name: "Détail", alt: "Ceinture détail", width: 4000, height: 2000 },
        ],
        size: ["85cm", "90cm", "95cm", "100cm", "105cm"],
        color: ["#795548", "#1A1A1A"],
        stock: 65,
        is_new: false,
        is_promo: false,
        discount_price: null,
        discount_percentage: null,
    },
    {
        name: "Sac à Dos Canvas",
        slug: "sac-a-dos-canvas",
        description: "Sac à dos en toile canvas robuste, compartiment laptop 15\", sangles rembourrées.",
        price: 23000,
        category_id: ID.cat4,
        image_url: "/images/img-10.jpg",
        images: [
            { url: "/images/img-10.jpg", name: "Face", alt: "Sac à dos face", width: 4000, height: 6000 },
            { url: "/images/img-33.jpg", name: "Côté", alt: "Sac à dos côté", width: 4000, height: 6000 },
            { url: "/images/img-14.jpg", name: "Dos", alt: "Sac à dos dos", width: 4000, height: 6000 },
        ],
        size: [],
        color: ["#607D8B", "#1A1A1A", "#6D4C41"],
        stock: 28,
        is_new: false,
        is_promo: true,
        discount_price: 18500,
        discount_percentage: 20,
    },
    {
        name: "Collier Perles Africaines",
        slug: "collier-perles-africaines",
        description: "Collier artisanal en perles de verre colorées, fait main au Bénin.",
        price: 7500,
        category_id: ID.cat4,
        image_url: "/images/img-20.jpg",
        images: [
            { url: "/images/img-20.jpg", name: "Face", alt: "Collier face", width: 4000, height: 4000 },
            { url: "/images/img-26.jpg", name: "Détail", alt: "Collier détail", width: 4000, height: 4000 },
        ],
        size: [],
        color: ["#FF6B6B", "#FFD600", "#43A047", "#1565C0"],
        stock: 50,
        is_new: true,
        is_promo: false,
        discount_price: null,
        discount_percentage: null,
    },
];

export async function GET(request: NextRequest) {

    const log = [];

    try {

        // 2. CRÉATION DES TABLES
        await pool.query('TRUNCATE products CASCADE;')

        // ── 3. PRODUCTS ───────────────────────────
        for (const p of products) {
            await pool.query(
                `INSERT INTO products
           ( name, slug, description, price, category_id, image_url, images,
            size, color, stock, is_new, is_promo, discount_price, discount_percentage)
         VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14)
         ON CONFLICT (id) DO NOTHING`,
                [
                    p.name, p.slug, p.description, p.price, p.category_id,
                    p.image_url,
                    JSON.stringify(p.images),
                    p.size, p.color,
                    p.stock, p.is_new, p.is_promo,
                    p.discount_price, p.discount_percentage,
                ]
            );
        }
        log.push(`✓ products : ${products.length} insérés`);


        return NextResponse.json({
            success: true,
            message: "Base de données remplie avec succès.",
            details: log,
        });
    } catch (error) {
        console.error("[SEED ERROR]", error);
        return NextResponse.json(
            {
                success: false,
                message: "Erreur lors du seed. Transaction annulée.",
                error: error.message,
            },
            { status: 500 }
        );

    }
}